version: "3"
services:
  server:
    build: .
    ports:
      - "5000:5000"
    networks:
      - node-ci-network
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
  redis:
    image: bitnami/redis
    networks: 
      - node-ci-network
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
networks:
  node-ci-network: