version: "3"
services:
  server:
    build: .
    ports:
      - "5000:5000"
    networks:
      - net
    environment:
      REDIS_HOST: redis://redis:6379
    depends_on:
      - redis
  redis:
    image: bitnami/redis
    networks: 
      - net
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
networks:
  net: