version: "3"
services:
  entry:
    image: nginx:stable-alpine
    networks:
      - net
    ports:
      - "80:80"
    depends_on:
      - client
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  redis:
    image: bitnami/redis
    networks: 
      - net
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
  server:
    build: .
    ports:
      - "5000:5000"
    networks:
      - net
    environment:
      REDIS_HOST: redis://redis:6379
    depends_on:
      - redis
  client:
    build: "./client"
    networks:
      - net
    depends_on:
      - server
networks:
  net: